export const setSessionRequest =
  ({ commit }, url) => commit('setSessionRequest')
export const setSessionUserDisplayName =
  ({ commit }, displayName) => commit('setSessionUserDisplayName')
export const setSessionUserEmail =
  ({ commit }, email) => commit('setSessionUserEmail')
export const setSessionUserPhotoUrl =
  ({ commit }, photoUrl) => commit('setSessionUserPhotoUrl')
export const setSessionUserUid =
  ({ commit }, uid) => commit('setSessionUserUid')

export const resetFund =
  ({ commit }) => commit('resetFund')
export const setFundAtoms =
  ({ commit }, value) => commit('setFundAtoms')
export const setFundBtcAddress =
  ({ commit }, value) => commit('setFundBtcAddress')
export const setFundBtcCost =
  ({ commit }, value) => commit('setFundBtcCost')
export const setFundProgress =
  ({ commit }, value) => commit('setFundProgress')
export const setFundUserName =
  ({ commit }, value) => commit('setFundUserName')
export const setFundUserEmail =
  ({ commit }, value) => commit('setFundUserEmail')
export const setFundUserNationality =
  ({ commit }, value) => commit('setFundUserNationality')
export const setFundUserPubkey =
  ({ commit }, value) => commit('setFundUserPubkey')
